### ISSUE TITLE
Profile setting

### ISSUE THREAD

**Issue by mcjackson18** [craftcms/commerce-sagepay#1]
Hi,

Is it possible to add a profile setting so there's option to use SagePay's 'LOW' profile for displaying forms in iframes?

See page 23 here - https://www.sagepay.co.uk/file/12246/download-document/SERVER_Integration_and_Protocol_Guidelines_010814.pdf?token=zlCqBGKB7BlA503YTOOtRsBXWKcI4aVrqNSETHDIspk

and line 83 here - https://github.com/thephpleague/omnipay-sagepay/blob/master/src/Message/AbstractRequest.php

Thanks

**Comment by andris-sevcenko** [comment]
@mcjackson18 I'll add it for the next version.

**Comment by andris-sevcenko** [comment]
Just released 1.1.0 with this added.
