### ISSUE TITLE
Multiple transactions recorded from gateway

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/commerce-sagepay#10]
I launched a shop a few weeks ago on latest Craft and Commerce and had a strange situation crop up. Craft recorded three successful transactions on a single order where in reality only a single transaction was made by the gateway. 

Each transactions is identical apart from the timestamp. 

The gateway in question is SagePay's redirect gateway and I contacted them to find out what they recorded from their side. Here's what they said:

> I have reviewed this transaction and can see we are receiving the following error - Connection failure cannot be handled for _[site_url]_/index.php?p=actions/commerce/webhooks/process-webhook&gateway=1&commerceTransactionHash=_[hash_string]_
> 
> What the logs show is that SagePay are attempting to contact your Notification URL. This is the URL you supply us with to notify you of the results of your transactions, to which your sever sends us a final acknowledgement post so we can finalise the order.
> 
> Since you have had multiple orders create, I believe that we are connecting to your NotifcationURL successfully however as we have not received your acknowledgement back to our notification post, this then causes the connection failure error message.
> 
> After a few attempts we did eventually receive the response back from your server, but this may be the reason why multiple orders were created in your system.

So I guess the server responded with a 5XX error for whatever reason the first couple of times resulting in no response to the gateway's message despite actually recording the transaction.

I would expect that Commerce should not be able to save an identical transaction more than once though it should still send the success message back to the gateway on subsequent requests in case of failure.

Also as a side note: There's no way to remove the extra transactions through the CP UI, which records should I remove to clear them from the database?

**Comment by pixelmachine** [comment]
@lukeholder is this a gateway issue?

The main symptom is that a transaction was able to be created numerous times despite the details of the transaction (i.e. response details) being identical. Isn't this something that Commerce validates?

It would have been great to diagnose why this happened (i.e. why did the gateway respond with an error despite correctly receiving the transaction response) but regardless of why it should be impossible. Right?

**Comment by nfourtythree** [comment]
@pixelmachine it would be great if you could get the information from Sagepay as to what response they received from Commerce.

This is a difficult one to debug without some real-world data. If you want to send over your database, composer.json and composer.lock files to support@craftcms.com that will give us some data to look at at least on this end of things.

Thanks.

**Comment by pixelmachine** [comment]
I have a screenshot of the related logs which is attached. I can't really send the DB, too much personal data. As soon as I get a chance I'll see if I can produce an anonymized or limited export.

**Comment by pixelmachine** [comment]
@nfourtythree ok, this has happened again.
I've looked in the logs and there are almost no entries for this date, no errors etc.

I've grabbed a couple of things that I guess may be of use (one log file and one db table) and I'll send those in now.

Please can you tell me how I should best delete the erroneous transactions? Can I just remove the duplicate transaction row in the DB? Will that have any other negative effect? It's messing up the reconciliation at the moment so I need them removed.

**Comment by nfourtythree** [comment]
Have just pushed a `2.1.0.2` release that should fix this issue.
