### ISSUE TITLE
Enable test mode depending on environment

### ISSUE THREAD

**Issue by billythekid** [craftcms/commerce-sagepay#12]
Hi all, 

Is there a way to put the gateway into test mode depending on environment? Perhaps in an init() method in a module/plugin?

I'd like to be able to test on staging but due to not allowing admin changes on staging I can't just toggle the setting in the settings. Not sure where to begin.

Cheers

**Comment by andris-sevcenko** [comment]
Pretty sure you should be able to pull it off with https://docs.craftcms.com/commerce/v2/gateway-config.html#gateway-configuration.

**Comment by billythekid** [comment]
Perfect, tested and that works great @andris-sevcenko.
