### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by sunscreem** [craftcms/commerce-sagepay#16]
### Description

Trying to upgrade to PHP8 but I'm getting the following:

```
- omnipay/sagepay 3.2.3 requires php ^5.6|^7 -> your php version (8.0.10) does not satisfy that requirement.
    - craftcms/commerce-sagepay 3.0.0 requires omnipay/sagepay ~3.0 -> satisfiable by omnipay/sagepay[3.2.3].
    - craftcms/commerce-sagepay is locked to version 3.0.0 and an update of this package was not requested.
```

I think the issue is with omnipay? 

Everything seems to work fine if I do a `--ignore-platform-reqs`

**Comment by sunscreem** [comment]
Any update on this?

**Comment by nfourtythree** [comment]
Hi @sunscreem 

This is an issue with the underlying `omnipay-sagepay` library. There is an issue relating to the support of PHP 8 for that library here: https://github.com/thephpleague/omnipay-sagepay/issues/167

Unfortunately, we are at the mercy of the package maintainers as to when this will be resolved as we have no control over that library.
