### ISSUE TITLE
Plugin does not support 'Basket' format and does not use Omnipay version 3.x

### ISSUE THREAD

**Issue by harnasz** [craftcms/commerce-sagepay#2]
SagePay has two methods to submit the basket, `Basket` and `BasketXML`.  Read more from the `thephpleague/omnipay-sagepay` docs [here](https://github.com/thephpleague/omnipay-sagepay#basket-format).

Also the current version of `3.x` where as this plugin uses `2.x`. 

We are going to raise a PR which adds support for the older `Basket` format which then allows Sage 50 Software Accounts Integration and to add support for `3.x`.

**Comment by andris-sevcenko** [comment]
> Also the current version of 3.x where as this plugin uses 2.x.
We are going to raise a PR which adds support for the older Basket format which then allows Sage 50 Software Accounts Integration and to add support for 3.x.

Bumping the required version to `^3.0` will, in turn, require `omnipay/common` version `~3.0`. `craftcms/commerce-omnipay`, however, requires `omnipay/common` version `~2.0`, so you'll have an unresolvable composer dependency conflict.

Making a new version of `craftcms/commerce-omnipay` that supports `omnipay/common 3.0` would probably take some work and, currently, we don't really have resources to do that at this moment.

This is not to deter you from adding support for `3.x` - I'm only pointing out that it might involve a bit more work than you're counting on, so you can better evaluate your development budget and whether it's worth updating to `3.x` at this moment.

As for the actual feature you're working on - I don't think there's a reason to hide it away in the configuration file - you can definitely add it as a setting [here](https://github.com/harnasz/commerce-sagepay/blob/master/src/templates/gatewaySettings.html) as well.

Once you have your code ready, definitely submit that PR.

**Comment by harnasz** [comment]
Thanks @andris-sevcenko  - I'll close this issue and raise a new one just for the basket format.
