### ISSUE TITLE
`EVENT_AFTER_ORDER_PAID` not triggered once payment is made

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/commerce-sagepay#21]
### Description

The dummy payment gateway works fine and triggers the `EVENT_AFTER_ORDER_PAID` event once payment is made on an order.
The SagePay gateway doesn't seem to trigger this address.

### Steps to reproduce

1. Listen for the `EVENT_AFTER_ORDER_PAID`  event
2. Make a payment on an order
3. Event is not triggered

### Additional info

- Commerce 3.4.10.1
- Sage Pay for Craft Commerce 3.0.0

**Comment by nfourtythree** [comment]
Hi @andrewhawkes 

Are you using `purchase` or `authorize` as your payment type for the gateway? Are you using the Direct or Server gateway?

I have just tested this and everything seems to be working as expected.

Used the Server gateway, tried it with both `purchase` and `authorize` with the following module code.

```php
Event::on(Order::class, Order::EVENT_AFTER_ORDER_PAID, function($event) {
    Craft::getLogger()->log('Order paid', Logger::LEVEL_INFO, 'Order');
});
```

And saw the following lines in the `web.log` file.

```
...
2022-02-11 02:06:22 [-][1][-][info][Order] Order paid
...
2022-02-11 02:09:07 [-][-][-][info][Order] Order paid
```

Thanks.

**Comment by andrewhawkes** [comment]
@nfourtythree yep this is working - the bug I have is a complete other issue. Sorry about that.
