### ISSUE TITLE
Large increase in 2008 : The Transaction timed-out.

### ISSUE THREAD

**Issue by terryupton** [craftcms/commerce-sagepay#23]
### Description
This might to be related to the plugin and might be a Sage issue. But I wanted to raise it for any advice or feedback or if others have experienced similar? 

So since the update of the plugin on one of our clients websites we have had reports and a large increase of failed transactions. All showing as `"2008 : The Transaction timed-out."`

We have managed to find many of these in the 'inactive carts' section following several customers raising issues about this.
The site has also taken many successful payment as well since it was updated. However, as a comparison to prior the update this is a significant increase in these errors. 

Using SagePay Server.

The customers are all reporting this:
- They get redirected to SagePay. 
- They enter their card details.
- They they get told by SagePay it is authorising the card.
- Then nothing happens it either stays with nothing to click or go OR (this was't clear) might redirect back to the site without nothing on the screen.

These transactions are also not even getting registered in SagePay account.

Anyone else experienced this or seeing similar issues?

**Comment by nfourtythree** [comment]
Hi @terryupton 

I am wondering if this could be along the same line as other issues people have seen. They have been related to the fact somewhere along the line they are setting `APPLY_3DSECURE_APPLY` (which is part of the underlying ominpay lib) to `1`. This "forces" 3D secure and has caused some issues with some banks that don't apply 3D secure. 

Removing this from any custom code would mean that it would default to `0` which essentially means "apply when needed"

Thanks.

**Comment by terryupton** [comment]
> Hi @terryupton
> 
> I am wondering if this could be along the same line as other issues people have seen. They have been related to the fact somewhere along the line they are setting `APPLY_3DSECURE_APPLY` (which is part of the underlying ominpay lib) to `1`. This "forces" 3D secure and has caused some issues with some banks that don't apply 3D secure.
> 
> Removing this from any custom code would mean that it would default to `0` which essentially means "apply when needed"
> 
> Thanks.

Thanks @nfourtythree - this is exactly what was causing the issue and it was myself who reported this the other day.
Thanks again.
