### ISSUE TITLE
Legacy 'Basket' format support.

### ISSUE THREAD

**Issue by ghost** [craftcms/commerce-sagepay#3]
SagePay has two methods to submit the basket, `Basket` and `BasketXML`.  Read more from the `thephpleague/omnipay-sagepay` docs [here](https://github.com/thephpleague/omnipay-sagepay#basket-format).

I'm going to raise a PR to fix this for  Omnipay version`2.x`.

**Comment by andris-sevcenko** [comment]
Just released 1.1.0 with this.
