### ISSUE TITLE
Strong Customer Authentication

### ISSUE THREAD

**Issue by kevadamson** [craftcms/commerce-sagepay#9]
Hi. Using SagePay Server. Just wondering if there are any steps required to ensure SCA compliance from 14/09/19?

**Comment by andris-sevcenko** [comment]
Doesn't seem like it: https://www.sagepay.co.uk/support/16/3d-secure-v2-what-do-customers-need-to-do

**Comment by kevadamson** [comment]
@andris-sevcenko Thanks for checking that for me :)
